### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by dhuppenkothen** [AstroHackWeek/AstroHackWeek2019#3]
Here are the milestones for making AHW 2019 happen!

- [x] Initial telecon with SOC mid-September (latest)
- [x] Website ready Sep 31 (also add workshop to respective lists, get Wiki ready a month before workshop)
- [x] Application form ready before Christmas
- [x] Application Open at AAS
- [x] Application Deadline Mar 15
- [x] First participant selection Mar 31 + funding ready 
- [x] Participant list ready mid-May
- [ ] AHW August/September

**Comment by davidwhogg** [comment]
Where's it going to be??
